name: Release Config

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  update_release_draft:
    permissions: 
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          configuration-path: .github/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
